<Project Sdk="Aspire.AppHost.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>616547e2-3a28-4c9d-8685-f4ac02581162</UserSecretsId>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hosts.Bff.MultiFrontend\Hosts.Bff.MultiFrontend.csproj" />
    <ProjectReference Include="..\Hosts.ServiceDefaults\Hosts.ServiceDefaults.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\migrations\UserSessionDb\UserSessionDb.csproj" />
    <ProjectReference Include="..\RemoteApis\Hosts.RemoteApi.DPoP\Hosts.RemoteApi.DPoP.csproj" />
    <ProjectReference Include="..\RemoteApis\Hosts.RemoteApi.Isolated\Hosts.RemoteApi.Isolated.csproj" />
    <ProjectReference Include="..\RemoteApis\Hosts.RemoteApi\Hosts.RemoteApi.csproj" />
    <ProjectReference Include="..\Hosts.Bff.DPoP\Hosts.Bff.DPoP.csproj" />
    <ProjectReference Include="..\Hosts.Bff.EF\Hosts.Bff.EF.csproj" />
    <ProjectReference Include="..\Hosts.Bff.InMemory\Hosts.Bff.InMemory.csproj" />
    <ProjectReference Include="..\Hosts.Bff.Performance\Hosts.Bff.Performance.csproj" />
    <ProjectReference Include="..\Blazor\PerComponent\Hosts.Bff.Blazor.PerComponent.Client\Hosts.Bff.Blazor.PerComponent.Client.csproj" />
    <ProjectReference Include="..\Blazor\PerComponent\Hosts.Bff.Blazor.PerComponent\Hosts.Bff.Blazor.PerComponent.csproj" />
    <ProjectReference Include="..\Blazor\WebAssembly\Hosts.Bff.Blazor.WebAssembly.Client\Hosts.Bff.Blazor.WebAssembly.Client.csproj" />
    <ProjectReference Include="..\Blazor\WebAssembly\Hosts.Bff.Blazor.WebAssembly\Hosts.Bff.Blazor.WebAssembly.csproj" />
    <ProjectReference Include="..\Hosts.IdentityServer\Hosts.IdentityServer.csproj" />
    <ProjectReference Include="..\..\templates\src\BffLocalApi\BffLocalApi.csproj" />
    <ProjectReference Include="..\..\templates\src\BffRemoteApi\BffRemoteApi.csproj" />
    <ProjectReference Include="..\..\templates\src\BffBlazorAutoRenderMode\BffBlazorAutoRenderMode\BffBlazorAutoRenderMode.csproj" />

  </ItemGroup>

</Project>
