##### Wrong Verbs #####
###
GET https://localhost:5001/connect/dcr
###
PUT https://localhost:5001/connect/dcr
###
DELETE  https://localhost:5001/connect/dcr

##### Malformed Requests ####
###
POST https://localhost:5001/connect/dcr
Content-Type: application/json

}

###
POST https://localhost:5001/connect/dcr

{ }

###
POST https://localhost:5001/connect/dcr
Content-Type: application/json

null

###
POST https://localhost:5001/connect/dcr
Content-Type: application/json

"bogus"


##### Semantic Errors #####
### Missing Grant Type
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"]
}

### Unsupported Grant Type
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["password"]
}

### Client creds with a redirect uri
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials"]
}

### Auth code without a redirect uri
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "grant_types": ["authorization_code"]
}

### Auth code without a redirect uri (multiple grant types)
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "grant_types": ["authorization_code", "client_credentials"]
}

### Client creds with refresh token
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "refresh_token"]
}

### JWK without private_key_jwt auth method
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"],
    "client_name": "example",
    "client_uri": "https://example.com",
    "default_max_age": 10000,
    "jwks": {"keys":[
        { "kty": "oct", "use": "sig", "kid": "1", "k": "nYA-IFt8xTsdBHe9hunvizcp3Dt7f6qGqudq18kZHNtvqEGjJ9Ud-9x3kbQ-LYfLHS3xM2MpFQFg1JzT_0U_F8DI40oby4TvBDGszP664UgA8_5GjB7Flnrlsap1NlitvNpgQX3lpyTvC2zVuQ-UVsXbBDAaSBUSlnw7SE4LM8Ye2WYZrdCCXL8yAX9vIR7vf77yvNTEcBCI6y4JlvZaqMB4YKVSfygs8XqGGCHjLpE5bvI-A4ESbAUX26cVFvCeDg9pR6HK7BmwPMlO96krgtKZcXEJtUELYPys6-rbwAIdmxJxKxpgRpt0FRv_9fm6YPwG7QivYBX-vRwaodL1TA", "alg": "HS256"}
    ]}
}


### private_key_jwt auth method without jwk
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"],
    "client_name": "example",
    "client_uri": "https://example.com",
    "default_max_age": 10000,
    "token_endpoint_auth_method": "private_key_jwt"
}

### Malformed jwks
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"],
    "client_name": "example",
    "client_uri": "https://example.com",
    "token_endpoint_auth_method": "private_key_jwt",
    "jwks": {"garbage": "nonsense"}
}

### Malformed jwks (null)
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"],
    "client_name": "example",
    "client_uri": "https://example.com",
    "token_endpoint_auth_method": "private_key_jwt",
    "jwks": {"keys": [null]}
}


### Malformed jwks (empty string)
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"],
    "client_name": "example",
    "client_uri": "https://example.com",
    "token_endpoint_auth_method": "private_key_jwt",
    "jwks": {"keys": [""]}
}


##### Valid Requests #####
###
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["authorization_code"]
}

### Multiple grant types
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"]
}


### Complete request
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"],
    "client_name": "example",
    "client_uri": "https://example.com",
    "default_max_age": 10000,
    "token_endpoint_auth_method": "private_key_jwt",
    "jwks": {"keys":[{"kty":"RSA","use":"sig","kid":"B6E26ACCE1DAC65C7E40FC26AAD2B157","e":"AQAB","n":"r_JV7t1CyyIR_DkYsqJ-zNDqxPD-hm7YvtAQd9is20PhDfRx1QtXoRs6yG2GM_GifitqPR6K6B3UxzyzY9CMVjwDr_66aIaq5-AsfXUnjotfHzjiyqlyVgpTtpsm21_iYcl65DkefS5I2I1jyIVY1AJg0AuIRX5IK4U4c0GQtJcHS7DFDnGFArWMup0gmH3KN2quYBmwN5p_MkVK_VWR8SP-YMdTn3-_zlz-bHdfZCn5Sfs35tP73ex-DVfquH9g0QZYIismggYsc3zOdC9ae3tmlK8XZfsf_INw9XcWdAa-rjy4LIJeUyWSgtMrAk-e6n9NkC1Q52_3HPsmt6-tvQ","alg":"RS256"}]}
}



### HMAC Secret in JWK
POST https://localhost:5001/connect/dcr
Content-Type: application/json

{
    "redirect_uris": ["https://example.com/callback"],
    "grant_types": ["client_credentials", "authorization_code", "refresh_token"],
    "client_name": "example",
    "client_uri": "https://example.com",
    "token_endpoint_auth_method": "private_key_jwt",
    "jwks": {"keys":[
        { "kty": "oct", "use": "sig", "kid": "1", "k": "nYA-IFt8xTsdBHe9hunvizcp3Dt7f6qGqudq18kZHNtvqEGjJ9Ud-9x3kbQ-LYfLHS3xM2MpFQFg1JzT_0U_F8DI40oby4TvBDGszP664UgA8_5GjB7Flnrlsap1NlitvNpgQX3lpyTvC2zVuQ-UVsXbBDAaSBUSlnw7SE4LM8Ye2WYZrdCCXL8yAX9vIR7vf77yvNTEcBCI6y4JlvZaqMB4YKVSfygs8XqGGCHjLpE5bvI-A4ESbAUX26cVFvCeDg9pR6HK7BmwPMlO96krgtKZcXEJtUELYPys6-rbwAIdmxJxKxpgRpt0FRv_9fm6YPwG7QivYBX-vRwaodL1TA", "alg": "HS256"}
    ]}
}

#TODO - Test other JWK algorithms


